site_name: Luis Vaez Portafolio
site_description: Portfolio personal de proyectos 
site_url: https://vaezgaming1-afk.github.io/PortafolioLuisVaez-IA/
repo_url: https://github.com/vaezgaming1-afk/PortafolioLuisVaez-IA

repo_name: ia-portfolio
site_dir: site

theme:
  name: material
  language: es
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs 
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - content.code.copy
  palette:
        - scheme: default
          primary: custom
          accent: custom
          toggle:
            icon: material/weather-night
            name: Modo oscuro
        - scheme: slate
          primary: custom
          accent: custom
          toggle:
            icon: material/white-balance-sunny
            name: Modo claro
extra_css:
  - assets/extra.css


plugins:
  - search
  - awesome-pages
  - macros 
  - git-revision-date-localized:
      enable_git_follow: false

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - footnotes
  - toc:
      permalink: true
      toc_depth: 2-3
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tasklist:
      custom_checkbox: true         # dibuja los checkboxes bonitos
      clickable_checkbox: true      # opcional: permite clicarlos (no persiste)



edit_uri: blob/main/docs/

extra_css:
  - assets/extra.css

nav:
  - Inicio: index.md
  - "Acerca de mí": acerca.md
  - Portfolio:
      - Índice: portfolio/index.md
      - 'Publicación': 'portfolio/1Publicacion.md'
      
      - "01 — EDA del Titanic...":
          - 'Práctica 1 (Principal)': 'portfolio/Practica1.md'
          - 'Práctica 1.2': 'portfolio/Practica1.2.md'
          - 'Práctica 1.3': 'portfolio/Practica1.3.md'

      - "02 — Feature Engineering...":
          - 'Práctica 2 (Principal)': 'portfolio/Practica2.md'
          - 'Práctica 2.1': 'portfolio/Practica2.1.md'
          - 'Práctica 2.2': 'portfolio/Practica2.2.md'

      - "03 — Regresión Lineal...":
          - 'Práctica 4 (Principal)': 'portfolio/Practica4.md'
          - 'Práctica 4.1': 'portfolio/Practica4.1.md'
          - 'Práctica 4.2': 'portfolio/Practica4.2.md'

      - "04 — Validación y Selección...":
          - 'Práctica 5 (Principal)': 'portfolio/Practica5.md'
          - 'Práctica 5.1': 'portfolio/Practica5.1.md'
          - 'Práctica 5.2': 'portfolio/Practica5.2.md'

      - "05 — Clustering y PCA...":
          - 'Práctica 6 (Principal)': 'portfolio/Practica6.md'
          - 'Práctica 6.1': 'portfolio/Practica6.1.md'
          - 'Práctica 6.2': 'portfolio/Practica6.2.md'
          
      - "Práctica 7": 
          - 'Práctica 7 (Principal)': 'portfolio/Practica7.md'
          - 'Práctica 7.1': 'portfolio/Practica7.1.md'
          - 'Práctica 7.2': 'portfolio/Practica7.2.md'
      
      - "Práctica 8":
          - 'Práctica 8 (Principal)': 'portfolio/Practica8.md'
          - 'Práctica 8.1': 'portfolio/Practica8.1.md'
          - 'Práctica 8.2': 'portfolio/Practica8.2.md'

      - "Práctica 9":
          - 'Práctica 9 (Principal)': 'portfolio/Practica9.md'
          - 'Práctica 9.1': 'portfolio/Practica9.1.md'

      - "Práctica 10":
          - 'Práctica 10 (Principal)': 'portfolio/Practica10.md'
          - 'Práctica 10.1': 'portfolio/Practica10.1.md'

      - "Práctica 11":
          - 'Práctica 11 (Principal)': 'portfolio/Practica11.md'
          - 'Práctica 11.1': 'portfolio/Practica11.1.md'

      - "Práctica 12":
          - 'Práctica 12 (Principal)': 'portfolio/Practica12.md'
          - 'Práctica 12.1': 'portfolio/Practica12.1.md'

      - "Práctica 13":
          - 'Práctica 13 (Principal)': 'portfolio/Practica13.md'
          - 'Práctica 13.1': 'portfolio/Practica13.1.md'

      - "Práctica 14":
          - 'Práctica 14 (Principal)': 'portfolio/Practica14.md'
          - 'Práctica 14.1': 'portfolio/Practica14.1.md'
          
      - 'Plantilla': 'portfolio/plantilla.md'
      
  - Recursos: recursos.md
  
docs_dir: docs

